app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# IbrowsNewsletter
ibrows_newsletter:
    resource: "@IbrowsNewsletterBundle/Controller/"
    type:     annotation
    prefix:   /newsletter

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"